name: Build MT7601U Module

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc kmod cpio flex bison libssl-dev wget

      - name: Prepare kernel source
        run: |
          mkdir -p ~/kernel
          cd ~/kernel
          # Télécharge le kernel source Huawei P10 (met ton lien direct ici si besoin)
          wget -O kernel.tar.gz "https://download-c1.huawei.com/download/downloadCenter?downloadId=B87082E9CE997D8645041978C5217002&version=F15A20CE67D1FE8501BD721465A67ACC&siteCode=worldwide"
          tar -xzf kernel.tar.gz --strip-components=1

      - name: Build MT7601U module
        run: |
          cd ~/kernel
          # Adapter la config selon ton kernel (4.9.111 arm64)
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- oldconfig || true
          make M=drivers/net/wireless/mediatek/mt7601u modules

      - name: Upload mt7601u.ko
        uses: actions/upload-artifact@v4
        with:
          name: mt7601u-ko
          path: drivers/net/wireless/mediatek/mt7601u/mt7601u.ko
